package com.micatechnologies.minecraft.ldib.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;

/**
 * Common client-side base for a rideable's model — a {@link ModelBase} whose wheels can be spun from
 * ground speed and whose lights can glow. {@link ModelBike} and {@link ModelScooter} both extend it so
 * the entity renderer and the rack / dock tile-entity renderers can hold one reference and draw
 * whichever variant is present (see {@link RideableModels}). Client-only, like everything in this
 * package.
 *
 * <p><b>Orientation.</b> All models here are authored with their <b>front toward −z</b>. {@link
 * RenderBike}'s minecart/boat transform (rotate {@code 180 − yaw}, then {@code scale(-1,-1,1)}) maps
 * model −z onto the world direction the rider faces, so front-at−z renders forward. (Earlier models
 * had the handlebars at +z, i.e. facing backwards — invisible in first person on the seated bike, but
 * glaring on the standing scooter.)</p>
 *
 * <p><b>Round-ish wheels.</b> {@link #buildWheel} makes a wheel as a ring of twelve short rim
 * segments sitting at the radius (a 12-gon tyre) plus a small hub — nothing crosses the centre, so
 * there is no pile of overlapping faces to z-fight and it reads as round. Spinning is just adding an
 * angle to every segment ({@link #spinWheel}). Optionally it also adds a handful of literal spokes
 * between the hub and the rim (radial, not crossing the centre either — same reasoning) for wheels big
 * enough that they read clearly, e.g. the bike's; see the {@code withSpokes} overload.</p>
 *
 * <p><b>Avoiding z-fighting.</b> Frame tubes all share the {@code x = ±(w/2)} side planes, so where
 * two of them overlap (at a joint) their faces fight. {@link #lug} drops a slightly-wider cube at a
 * joint to bury those overlaps; give any part that would sit coplanar with a lug a different width so
 * their faces never coincide.</p>
 */
public abstract class ModelRideable extends ModelBase {

    // --- Per-MATERIAL UV atlas ----------------------------------------------------------------
    //
    // Skins are painted per MATERIAL, not per box: a handful of solid-colour (softly shaded)
    // regions on one 128×64 atlas, and every part is built at the texture offset of the material
    // it is made of. Parts that share a material share ONE offset (they overlap in UV on purpose —
    // they just share the colour + shading); different materials get non-overlapping regions.
    //
    // A W×H×D box unwraps to a (2D+2W)-wide × (D+H)-tall footprint at its offset (MC's box UV
    // layout: top/bottom faces in the top D-tall strip, the four sides in the H-tall strip below).
    // Each region below is sized to the LARGEST box that uses it, across both models; the matching
    // PNGs (generated by tools/gen_skins.py) paint exactly these rects. Both {@link ModelBike} and
    // {@link ModelScooter} set textureWidth/Height to these values.
    //
    //   material  offset (u,v)   region w×h   used by (largest footprint)
    //   --------  ------------   ----------   ----------------------------------------------------
    //   TYRE      (0, 0)         12 × 8       wheel rim segments + hub (bike hub 10×8, seg 12×7)
    //   FRAME     (16, 0)        12 × 20      bike frame tubes + lugs; scooter stem/fork/lug
    //                                         (scooter stem 8×20, lug 12×6)
    //   ACCENT    (32, 0)        26 × 10      bike saddle + handlebar; scooter deck + handlebar
    //                                         (scooter deck 26×10, handlebar 24×4)
    //   METAL     (64, 0)        16 × 5       scooter fender + small hardware (fender 16×5)
    //
    // Layout has ≥4 px of unpainted gap between regions, so a part sampling to the exact edge of
    // its footprint never bleeds into a neighbouring material. To move/resize a region, change the
    // offset here AND the rect in tools/gen_skins.py together.
    public static final int ATLAS_W = 128, ATLAS_H = 64;
    protected static final int TYRE_U = 0,   TYRE_V = 0;
    protected static final int FRAME_U = 16, FRAME_V = 0;
    protected static final int ACCENT_U = 32, ACCENT_V = 0;
    protected static final int METAL_U = 64, METAL_V = 0;

    /** Rim segments per wheel — a 12-gon tyre. */
    private static final int WHEEL_SEGMENTS = 12;
    private static final double SEGMENT_STEP = 2.0 * Math.PI / WHEEL_SEGMENTS; // 30°
    private static final int RIM_DEPTH = 2; // radial thickness of the tyre, px

    /** Spokes per wheel, evenly spaced, for {@link #buildWheel(float, float, int, int, int, int, boolean)}. */
    private static final int SPOKE_COUNT = 6;
    private static final double SPOKE_STEP = 2.0 * Math.PI / SPOKE_COUNT; // 60°
    private static final int SPOKE_THICK = 1; // px, both cross-section dims

    /** Spin the wheels by {@code wheelAngle} radians — called by renderers from ground speed. */
    public abstract void setWheelSpin(float wheelAngle);

    /**
     * Cosmetic front-assembly steer angle in degrees, set by the renderer each frame (see {@code
     * EntityBike#steerAngle}). The concrete models rotate their fork/front-wheel/stem/handlebars/
     * headlight by this much about the steering axis (see {@link #beginSteer}); everything else stays
     * put. Purely presentational — nothing here feeds back into movement.
     */
    private float steerAngle;

    /** Set the front-assembly steer angle (degrees) applied on the next {@link #beginSteer}. */
    public void setSteerAngle(float degrees) {
        this.steerAngle = degrees;
    }

    /**
     * Begin a steering rotation of the front assembly: push a matrix and rotate {@link #steerAngle}
     * degrees about the <b>vertical (Y) axis through model x=0, z={@code pivotZ}</b> (the head tube /
     * stem). Render the steering parts, then call {@link #endSteer} to pop.
     *
     * <p>Because {@link ModelRenderer#render(float)} bakes {@code scale} (0.0625) into vertex
     * positions rather than pushing a GL scale, a {@code GlStateManager.translate} here is in those
     * same baked units — so the model-space pivot {@code z} is reached by translating {@code
     * pivotZ * scale}. A Y-axis rotation only needs the pivot's x and z; both models put the axis at
     * x=0, so only z is translated. The classic pivot form is T(pivot)·R·T(−pivot).</p>
     */
    protected void beginSteer(float scale, float pivotZ) {
        GlStateManager.pushMatrix();
        GlStateManager.translate(0.0F, 0.0F, pivotZ * scale);
        GlStateManager.rotate(this.steerAngle, 0.0F, 1.0F, 0.0F);
        GlStateManager.translate(0.0F, 0.0F, -pivotZ * scale);
    }

    /** End the {@link #beginSteer} rotation — pops the matrix so later (rear) parts are unaffected. */
    protected void endSteer() {
        GlStateManager.popMatrix();
    }

    /**
     * Draw this rideable's emissive light lenses — a white headlight and a red brake light — glowing at
     * {@code intensity} (1 = full; lower dims them, e.g. a bike idling in a share dock). Variants
     * without lights (the pedal bicycle) are simply never asked to draw them; see {@link
     * com.micatechnologies.minecraft.ldib.entity.BikeVariant#hasLights()}.
     */
    public abstract void renderLights(float scale, boolean headlightOn, boolean brakeLightOn, float intensity);

    // --- Model-building helpers --------------------------------------------------------------

    /**
     * A tube lying in the bike's centre plane (x = 0), from {@code (ay, az)} to {@code (by, bz)} in
     * model space, {@code w} pixels thick. Used for every frame member; since they all lie in the
     * centre plane, a single rotation about the axle (X) aims each one.
     */
    protected ModelRenderer tube(float ay, float az, float by, float bz, int w) {
        return tube(ay, az, by, bz, w, 0.0F, 0, 0);
    }

    /**
     * As {@link #tube(float, float, float, float, int)} but sampling the material region at texture
     * offset {@code (texU, texV)} instead of the default (0,0).
     */
    protected ModelRenderer tube(float ay, float az, float by, float bz, int w, int texU, int texV) {
        return tube(ay, az, by, bz, w, 0.0F, texU, texV);
    }

    /**
     * As {@link #tube(float, float, float, float, int)} but grown (or shrunk, if {@code grow} is
     * negative) uniformly by {@code grow} px on every face — used to make a {@code w}-px tube render a
     * fraction thinner than a whole pixel (e.g. the scooter's slimmer stem/handlebars).
     */
    protected ModelRenderer tube(float ay, float az, float by, float bz, int w, float grow) {
        return tube(ay, az, by, bz, w, grow, 0, 0);
    }

    /**
     * Full form: a {@code grow}-adjusted tube sampling the material region at {@code (texU, texV)}.
     * The UV footprint is computed from the integer {@code w}/length only — {@code grow} adjusts the
     * geometry, not the mapping — so a fractional {@code grow} does not change which region is sampled.
     */
    protected ModelRenderer tube(float ay, float az, float by, float bz, int w, float grow,
                                 int texU, int texV) {
        float dy = by - ay;
        float dz = bz - az;
        int len = Math.max(1, Math.round((float) Math.sqrt(dy * dy + dz * dz)));
        ModelRenderer t = new ModelRenderer(this, texU, texV);
        t.addBox(-w / 2.0F, 0.0F, -w / 2.0F, w, len, w, grow);
        t.setRotationPoint(0.0F, ay, az);
        t.rotateAngleX = (float) Math.atan2(dz, dy);
        return t;
    }

    /** A plain box at the model origin (rotation point 0,0,0) from an offset with px dimensions. */
    protected ModelRenderer box(float ox, float oy, float oz, int w, int h, int d) {
        return box(ox, oy, oz, w, h, d, 0, 0);
    }

    /** As {@link #box(float, float, float, int, int, int)} but sampling the region at {@code (texU, texV)}. */
    protected ModelRenderer box(float ox, float oy, float oz, int w, int h, int d, int texU, int texV) {
        ModelRenderer b = new ModelRenderer(this, texU, texV);
        b.addBox(ox, oy, oz, w, h, d);
        b.setRotationPoint(0.0F, 0.0F, 0.0F);
        return b;
    }

    /** A joint cube at {@code (y, z)}, {@code size} px on a side, to bury overlapping tube ends. */
    protected ModelRenderer lug(float y, float z, int size) {
        return lug(y, z, size, 0, 0);
    }

    /** As {@link #lug(float, float, int)} but sampling the material region at {@code (texU, texV)}. */
    protected ModelRenderer lug(float y, float z, int size, int texU, int texV) {
        ModelRenderer l = new ModelRenderer(this, texU, texV);
        l.addBox(-size / 2.0F, -size / 2.0F, -size / 2.0F, size, size, size);
        l.setRotationPoint(0.0F, y, z);
        return l;
    }

    /**
     * A round-ish wheel centred on the axle at {@code (ay, az)}: {@code radius} px, {@code tireWidth}
     * px across (the axle direction — keep this thinner than the frame). Built as a 12-segment rim ring
     * (each segment a short tangential slab at the radius) plus a small hub, so nothing overlaps at the
     * centre. Returns the segments + hub; render as a group and spin with {@link #spinWheel}.
     */
    protected ModelRenderer[] buildWheel(float ay, float az, int radius, int tireWidth) {
        return buildWheel(ay, az, radius, tireWidth, 0, 0);
    }

    /**
     * As {@link #buildWheel(float, float, int, int)} but every rim segment and the hub sample the
     * material region at {@code (texU, texV)} — the tyre colour. All 13 parts intentionally share the
     * one offset. No spokes (see the 7-arg overload) — used as-is by the scooter's small wheels, where
     * spokes at radius 3 aren't worth the extra geometry.
     */
    protected ModelRenderer[] buildWheel(float ay, float az, int radius, int tireWidth, int texU, int texV) {
        return buildWheel(ay, az, radius, tireWidth, texU, texV, false);
    }

    /**
     * Full form: as {@link #buildWheel(float, float, int, int, int, int)}, optionally adding {@link
     * #SPOKE_COUNT} thin radial spokes (FRAME-coloured, for a metallic contrast against the dark tyre)
     * between the hub and the rim — close enough to touch both without entering either one's volume, so
     * no spoke face ever sits exactly on a rim or hub face (that would z-fight; see class docs). Spokes
     * carry their own base angle independent of their index in the returned array (see {@link
     * WheelPart}), so they don't need to line up with the 12 rim segments to spin correctly.
     */
    protected ModelRenderer[] buildWheel(float ay, float az, int radius, int tireWidth, int texU, int texV,
                                          boolean withSpokes) {
        int sideLen = Math.max(2, Math.round(2.0F * radius * (float) Math.sin(Math.PI / WHEEL_SEGMENTS)) + 1);
        int total = WHEEL_SEGMENTS + 1 + (withSpokes ? SPOKE_COUNT : 0);
        ModelRenderer[] parts = new ModelRenderer[total];
        for (int i = 0; i < WHEEL_SEGMENTS; i++) {
            float baseAngle = (float) (i * SEGMENT_STEP);
            WheelPart seg = new WheelPart(this, texU, texV, baseAngle);
            // A slab at the top of the wheel (−y is up), thin radially (RIM_DEPTH), long tangentially.
            // Adjacent segments overlap at the corners and would share the x = ±tireWidth/2 side plane
            // (→ z-fighting); nudge odd segments a third of a pixel in x so no two neighbours are
            // coplanar. The tyre reads the same but the flicker is gone.
            float xNudge = (i % 2 == 0) ? 0.0F : 0.34F;
            seg.addBox(-tireWidth / 2.0F + xNudge, -radius, -sideLen / 2.0F, tireWidth, RIM_DEPTH, sideLen);
            seg.setRotationPoint(0.0F, ay, az);
            seg.rotateAngleX = baseAngle;
            parts[i] = seg;
        }
        int hub = Math.min(4, radius);
        WheelPart h = new WheelPart(this, texU, texV, 0.0F);
        h.addBox(-tireWidth / 2.0F, -hub / 2.0F, -hub / 2.0F, tireWidth, hub, hub);
        h.setRotationPoint(0.0F, ay, az);
        parts[WHEEL_SEGMENTS] = h;

        if (withSpokes) {
            // Inner end sits right at the hub's edge, outer end stops right at the rim's inner face —
            // touching both (so the spoke visually connects hub to rim) without overlapping either
            // one's box, which is what would put a spoke face exactly on a hub/rim face.
            int innerR = hub / 2;
            int outerR = Math.max(innerR + 1, radius - RIM_DEPTH);
            int spokeLen = outerR - innerR;
            for (int k = 0; k < SPOKE_COUNT; k++) {
                float baseAngle = (float) (k * SPOKE_STEP);
                WheelPart spoke = new WheelPart(this, FRAME_U, FRAME_V, baseAngle);
                // Same alternating-nudge trick as the rim segments, in case a small hub radius ever
                // crowds spokes close enough together near the centre to coincide.
                float xNudge = (k % 2 == 0) ? 0.0F : 0.34F;
                spoke.addBox(-SPOKE_THICK / 2.0F + xNudge, -outerR, -SPOKE_THICK / 2.0F,
                    SPOKE_THICK, spokeLen, SPOKE_THICK);
                spoke.setRotationPoint(0.0F, ay, az);
                spoke.rotateAngleX = baseAngle;
                parts[WHEEL_SEGMENTS + 1 + k] = spoke;
            }
        }
        return parts;
    }

    /**
     * A {@link ModelRenderer} that remembers its own unspun base angle around the axle, so {@link
     * #spinWheel} can re-aim every part in a wheel uniformly by adding {@code spin} to that stored angle
     * instead of deriving it from the part's position in the array. Plain rim segments and the hub still
     * use {@code i * SEGMENT_STEP} for their base angle (unchanged from before this existed — see
     * {@link #buildWheel}), so they spin exactly as they always did; spokes use their own {@code
     * k * SPOKE_STEP} instead, which needs a spacing the shared 12-segment index scheme can't express.
     */
    private static final class WheelPart extends ModelRenderer {
        private final float baseAngle;

        WheelPart(ModelBase model, int texU, int texV, float baseAngle) {
            super(model, texU, texV);
            this.baseAngle = baseAngle;
        }
    }

    /** Re-aim every part of a wheel (rim segments, hub, and spokes if present) so the whole wheel is
     *  rotated by {@code spin} radians, each part keeping its own base angle (see {@link WheelPart}). */
    protected static void spinWheel(ModelRenderer[] wheel, float spin) {
        for (ModelRenderer part : wheel) {
            WheelPart wp = (WheelPart) part;
            wp.rotateAngleX = wp.baseAngle + spin;
        }
    }

    /** Render every part in a group (e.g. a wheel's planks). */
    protected static void renderGroup(ModelRenderer[] parts, float scale) {
        for (ModelRenderer part : parts) {
            part.render(scale);
        }
    }

    /** Bright white for a headlight, red for a brake light. */
    private static final float[] HEAD_RGB = {1.0F, 1.0F, 0.95F};
    private static final float[] BRAKE_RGB = {1.0F, 0.05F, 0.05F};
    /** Dark grey the light housings (permanent hardware) are drawn in. */
    private static final float[] HARDWARE_RGB = {0.24F, 0.24F, 0.27F};

    /**
     * Draw solid, always-present hardware (e.g. the light housings) in a flat dark grey with normal
     * world lighting — so a light reads as a real fixture bolted to the bike, not a blob that only
     * exists when lit. Call from {@code render}, after the textured parts.
     */
    protected static void renderHardware(float scale, ModelRenderer... parts) {
        GlStateManager.disableTexture2D();
        GlStateManager.color(HARDWARE_RGB[0], HARDWARE_RGB[1], HARDWARE_RGB[2], 1.0F);
        for (ModelRenderer part : parts) {
            part.render(scale);
        }
        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
        GlStateManager.enableTexture2D();
    }

    /**
     * Render the emissive lenses that sit in the (always-present) housings: a bright full-brightness
     * core plus an additive translucent glow that flares outward. Texture and lighting are off and the
     * lightmap is forced full-bright, then all restored.
     */
    protected static void renderLightFixtures(float scale,
                                              boolean headlightOn, ModelRenderer headLens, ModelRenderer headGlow,
                                              boolean brakeLightOn, ModelRenderer brakeLens, ModelRenderer brakeGlow,
                                              float intensity) {
        if (!headlightOn && !brakeLightOn) {
            return;
        }
        float i = Math.max(0.0F, Math.min(1.0F, intensity));
        float lastX = OpenGlHelper.lastBrightnessX;
        float lastY = OpenGlHelper.lastBrightnessY;

        GlStateManager.disableTexture2D();
        GlStateManager.disableLighting();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0F, 240.0F);

        // Bright, opaque lens cores.
        if (headlightOn) {
            GlStateManager.color(HEAD_RGB[0] * i, HEAD_RGB[1] * i, HEAD_RGB[2] * i, 1.0F);
            headLens.render(scale);
        }
        if (brakeLightOn) {
            GlStateManager.color(BRAKE_RGB[0] * i, BRAKE_RGB[1] * i, BRAKE_RGB[2] * i, 1.0F);
            brakeLens.render(scale);
        }

        // Additive, translucent glow flares — bloom outward from the lens without occluding.
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE);
        GlStateManager.depthMask(false);
        if (headlightOn) {
            GlStateManager.color(HEAD_RGB[0], HEAD_RGB[1], HEAD_RGB[2], 0.55F * i);
            headGlow.render(scale);
        }
        if (brakeLightOn) {
            GlStateManager.color(BRAKE_RGB[0], BRAKE_RGB[1], BRAKE_RGB[2], 0.45F * i);
            brakeGlow.render(scale);
        }
        GlStateManager.depthMask(true);
        GlStateManager.disableBlend();

        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, lastX, lastY);
        GlStateManager.enableLighting();
        GlStateManager.enableTexture2D();
    }
}
