package com.micatechnologies.minecraft.ldib.block;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Invariants for the bike-rack styles. {@link RackStyle} happens to be pure data with no Minecraft
 * types, so it can be pinned on a bare JVM alongside the physics tests — worth doing, because this is
 * the layer where the multi-block rack bug hid: the models were authored 1×1 while the collision boxes
 * spanned three blocks, and nothing in the compiler, the unit suite or the dedicated-server smoke test
 * had any opinion about it.
 *
 * <p>These do not check that a rack looks <i>good</i> — that needs an eyeball. They check the things
 * that are provably wrong when they break: a bike parked outside the blocks it belongs to, a capacity
 * that disagrees with the slots, or a style quietly losing its parking spots.</p>
 */
class RackStyleTest {

    @Test
    void everyStyleHoldsAtLeastOneBike() {
        for (RackStyle style : RackStyle.values()) {
            assertTrue(style.capacity() >= 1, style + " should hold at least one bike");
        }
    }

    @Test
    void capacityAlwaysMatchesTheSlotCount() {
        for (RackStyle style : RackStyle.values()) {
            assertEquals(style.slots().length, style.capacity(),
                style + ": capacity() must be derived from the slots, never hard-coded alongside them");
        }
    }

    @Test
    void everySlotSitsWithinTheBlocksTheRackActuallyOccupies() {
        // A rack of length L covers local X in [-0.5, L-0.5]: the master block is centred on 0 and each
        // extension adds one block along the facing. A slot outside that renders a bike parked in mid-air
        // past the end of the rack, which is exactly the sort of thing that survives review by looking
        // plausible in a diff.
        for (RackStyle style : RackStyle.values()) {
            double min = -0.5D;
            double max = style.length() - 0.5D;
            for (RackStyle.Slot slot : style.slots()) {
                assertTrue(slot.along >= min && slot.along <= max,
                    style + " slot at along=" + slot.along + " falls outside the rack's footprint ["
                        + min + ", " + max + "] for length " + style.length());
            }
        }
    }

    @Test
    void slotsDoNotOverlapEachOther() {
        // Bikes are rendered near full size, so two slots closer than roughly a bike's width clip into
        // each other. 0.5 blocks is the practical floor found while spacing the wave and grid racks.
        for (RackStyle style : RackStyle.values()) {
            RackStyle.Slot[] slots = style.slots();
            for (int i = 0; i < slots.length; i++) {
                for (int j = i + 1; j < slots.length; j++) {
                    double gap = Math.abs(slots[i].along - slots[j].along)
                        + Math.abs(slots[i].across - slots[j].across);
                    assertTrue(gap >= 0.5D,
                        style + " slots " + i + " and " + j + " are only " + gap
                            + " blocks apart; near-full-size bikes will clip");
                }
            }
        }
    }

    @Test
    void theWideStylesSpanThreeBlocksAndHoldFive() {
        // Wave and grid are the wide racks. If either drops back to length 1, its block models
        // (bike_rack_<style>_0/_1/_2, generated by tools/gen_rack_models.py) are wrong too.
        for (RackStyle style : new RackStyle[] {RackStyle.WAVE, RackStyle.GRID}) {
            assertEquals(3, style.length(), style + " is a wide rack and should span three blocks");
            assertEquals(5, style.capacity(), style + " should hold five bikes");
        }
    }

    @Test
    void theSingleBlockStylesStayOneBlock() {
        // A ring, post or toast rack is deliberately smaller than a wave or grid rack.
        for (RackStyle style : new RackStyle[] {RackStyle.HOOP, RackStyle.POST, RackStyle.CLASSIC}) {
            assertEquals(1, style.length(), style + " is meant to stay a single block");
        }
    }
}
